<?php
const BASE_URL = 'http://api.weatherapi.com/v1/';
const FORECAST_DAYS = [7, 14];
const ALLOWED_URL_PARAMS = ['action', 'date'];
const JS_PATH = DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR;
const CSS_PATH = DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR;
const IMG_PATH = DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR;
const MODALS_PATH = '../app' . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR . 'modals' . DIRECTORY_SEPARATOR;
const PAGES_PATH = '../app' . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR . 'pages' . DIRECTORY_SEPARATOR;
const COMMON_PATH = '../app' . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR . 'common' . DIRECTORY_SEPARATOR;
const UTILS_PATH = '../app' . DIRECTORY_SEPARATOR . 'utils' . DIRECTORY_SEPARATOR;
const CORE_PATH = '../app' . DIRECTORY_SEPARATOR . 'core' . DIRECTORY_SEPARATOR;
const CONTROLLER_PATH = '../app' . DIRECTORY_SEPARATOR . 'controllers' . DIRECTORY_SEPARATOR;
const MODEL_PATH = '../app' . DIRECTORY_SEPARATOR . 'models' . DIRECTORY_SEPARATOR;

const CLASS_PATHS = [
    UTILS_PATH,
    CORE_PATH,
    CONTROLLER_PATH,
    MODEL_PATH,
];
