<?php
const FORECAST_DAYS = [7, 14];
const JS_PATH = DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR;
const CSS_PATH = DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR;
const IMG_PATH = DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR;
const MODALS_PATH = '..' . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR . 'modals' . DIRECTORY_SEPARATOR;
const PAGES_PATH = '..' . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR . 'pages' . DIRECTORY_SEPARATOR;
const COMMON_PATH = '..' . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR . 'common' . DIRECTORY_SEPARATOR;
